---

- hosts: gotty
  become: True
  roles:
    - role: gotty
      tags:
        - gotty
- hosts: all
  become: True
  roles:
    - role: external/nginx 
      tags:
        - nginx
    - role: graphical
      tags:
        - graphical
    - role: external/docker
      tags:
        - docker
    # - role: mysql-prereq
    #   tags:
    #     - mysql
    #     - guacamole
    - role: external/mysql
      tags:
        - mysql
        - guacamole-full
    - role: vnc
      tags:
        - vnc
        - guacamole-all
# - hosts: guacamole
    - role: external/guacamole
      tags:
        - guacamole
        - guacamole-full

