---

- name: nginx
  src: https://github.com/geerlingguy/ansible-role-nginx
  version: 2.6.2
- name: docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.2
- name: guacamole
  src: https://github.com/mrlesmithjr/ansible-guacamole
# - name: mysql
#  src: https://github.com/mrlesmithjr/ansible-mysql
- name: mysql
  src: https://github.com/geerlingguy/ansible-role-mysql
  
