---

ansible_python_interpreter: /usr/bin/python3

nginx_remove_default_vhost: True
nginx_vhosts:
- listen: 80
  server_name: _
  extra_parameters: |
    location / {
          proxy_pass         http://127.0.0.1:9090;

          proxy_buffering off;
          proxy_pass_header Server;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
    }
