---

nginx_remove_default_vhost: True
nginx_vhosts:
- listen: 80
  server_name: _
  extra_parameters: |
    location / {
          proxy_pass         http://127.0.0.1:9090;

          proxy_buffering off;
          proxy_pass_header Server;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
    }
    location /guacamole/ {
          proxy_pass http://127.0.0.1:8080/guacamole/;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          access_log off;
    }

pri_domain_name: "{{ ansible_host }}.nip.io"

mysql_users:
  - name: guacamole
    password: guacamole
